package excepion;

public class FinallyExcep {
	public static void main(String [] args)
	{
		try {
			m1();
		}
		catch(NullPointerException n)
		{
			System.out.println("Exception handled");
		}
		finally
		{
			System.out.println("Thankyou");
		}
	}
	public static void m1() throws NullPointerException
	{
		String  s = null;
		System.out.println(s.length());
	}
}
